<?php

namespace ConferenceTools\Checkin\Form;

use Zend\Form\Element\Submit;
use Zend\Form\Element\Text;
use Zend\Form\Form;

class SearchForm extends Form
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->add(new Text('firstName', ['label' => 'First name']));
        $this->add(new Text('lastName', ['label' => 'Last name']));
        $this->add(new Text('email', ['label' => 'Email']));
        $this->add(new Text('ticketId', ['label' => 'Ticket Id']));
        $this->add(new Submit('submit', ['label' => 'Search']));
    }
}